personal/Controllers/ServicosController.cs
using personal.Models;
using personal.Repositório;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace personal.Controllers
{
    public class ServicosController : Controller
    {
        //1 - MUSCULACAO
        //2 - NATAÇÃO
        //3 - CICLISMO
        //4 - CORRIDA
        //5 - MUAY THAI
        //6 - ZUMBA

        // GET: Servicos
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MeusServicos()
        {
            return View();
        }
        public ActionResult Autorizar()
        {
            List<Colaborador> lista = listagem.listaAutorizaColaborador();
            return View(lista);
        }
        public ActionResult AutorizarEsporte()
        {
            List<Esporte> lista = listagem.listaAutorizaEsporte();
            ViewBag.ItemData = lista.ToList();
            return Json(ViewBag.ItemData, JsonRequestBehavior.AllowGet);
        }
        public void salvaAutorizacao(int idColab)
        {
            listagem.salvaAutorizacao(idColab);
        }
        public void bloqueiaAutorizacao(int idColab)
        {
            listagem.bloqueiaAutorizacao(idColab);
        }
        public ActionResult MuayThai()
        {
            List<Colaborador> colab = listagem.listaPersonal(1);
            Session["servico"] = 1;
            if (colab.Count == 0)
            {
                ViewBag.Message = "Atualmente não encontramos nenhum personal que ofereça essa modalidade.";
            }
            ViewBag.ItemData = colab.ToList();
            return View("~/Views/Servicos/Index.cshtml");
        }
        public ActionResult Funcional()
        {
            List<Colaborador> colab = listagem.listaPersonal(2);
            Session["servico"] = 2;
            if (colab.Count == 0)
            {
                ViewBag.Message = "Atualmente não encontramos nenhum personal que ofereça essa modalidade.";
            }
            ViewBag.ItemData = colab.ToList();
            return View("~/Views/Servicos/Index.cshtml");
        }
        public ActionResult Corrida()
        {
            List<Colaborador> colab = listagem.listaPersonal(3);
            Session["servico"] = 3;
            if (colab.Count == 0)
            {
                ViewBag.Message = "Atualmente não encontramos nenhum personal que ofereça essa modalidade.";
            }
            ViewBag.ItemData = colab.ToList();
            return View("~/Views/Servicos/Index.cshtml");
        }
        public ActionResult Slackline()
        {
            List<Colaborador> colab = listagem.listaPersonal(4);
            Session["servico"] = 4;
            if (colab.Count == 0)
            {
                ViewBag.Message = "Atualmente não encontramos nenhum personal que ofereça essa modalidade.";
            }
            ViewBag.ItemData = colab.ToList();
            return View("~/Views/Servicos/Index.cshtml");
        }
        public ActionResult Surf()
        {
            List<Colaborador> colab = listagem.listaPersonal(5);
            Session["servico"] = 5;
            if (colab.Count == 0)
            {
                ViewBag.Message = "Atualmente não encontramos nenhum personal que ofereça essa modalidade.";
            }
            ViewBag.ItemData = colab.ToList();
            return View("~/Views/Servicos/Index.cshtml");
        }
        public ActionResult Musculacao()
        {
            List<Colaborador> colab = listagem.listaPersonal(6);
            Session["servico"] = 6;
            if (colab.Count == 0)
            {
                ViewBag.Message = "Atualmente não encontramos nenhum personal que ofereça essa modalidade.";
            }
            ViewBag.ItemData = colab.ToList();
            return View("~/Views/Servicos/Index.cshtml");
        }
        
        public ActionResult SaibaMais(int id)
        {
            var tes = Session["servico"];
            Colaborador list = listagem.listaSaibaMais(id);
            list.DATA_NASCIMENTO_FORMATADA = list.DATA_NASCIMENTO.ToString("dd/MM/yyyy");
            return View(list);
        }
        [HttpPost]
        public void NovaModalidade(String esporte, CadastroHorarios model)
        {
            int now = 0;
            int final = 0;
            DateTime dataFormatada;
            DateTime dataTransf;
            DateTime dataFinal;
            listagem.insereModalidades(int.Parse(Session["ID"].ToString()), int.Parse(esporte));
            int x = 0;
            for (int i = 0; i < ((IList)model.data).Count; i++)
            {


                
                if (model.data[i] == "")
                {
                    if (model.frequencia[x] == "")
                    {
                        model.frequencia[x] = "mensal";
                    }
                    //String dataAtual = DateTime.Now.ToString("dd/MM/yyyy");
                    //dataTransf = DateTime.Parse(dataAtual);
                    //dataFinal = dataTransf.AddMonths(model.meses[x]);
                    //String data;
                    //String dataForm;
                    //CultureInfo culture = new CultureInfo("pt-BR");
                    //DateTimeFormatInfo dtfi = culture.DateTimeFormat;



                    for (int y = 0; y < model.horarios.Count; y++)
                    {
                        if (model.horarios[y] != "end")
                        {
                            String dataAtual = DateTime.Now.ToString("dd/MM/yyyy");
                            dataTransf = DateTime.Parse(dataAtual);
                            dataFinal = dataTransf.AddMonths(model.meses[x]+1);
                            String data;
                            String dataForm;
                            CultureInfo culture = new CultureInfo("pt-BR");
                            DateTimeFormatInfo dtfi = culture.DateTimeFormat;
                            dataForm = dataTransf.ToString("dd/MM/yyyy") + " " + model.horarios[y];
                            dataTransf = DateTime.Parse(dataForm);
                            while (dataTransf <= dataFinal)
                            {
                                data = dtfi.GetDayName(dataTransf.DayOfWeek);
                                now = DateTime.Now.Month;
                                final = dataFinal.Month;
                                if (dataTransf.Month != now && dataTransf.Month != final)
                                {
                                    if (model.diaSemana[x] == data)
                                    {

                                        ModalidadesAulas.NovaModalidade(int.Parse(esporte), int.Parse(Session["ID"].ToString()), dataTransf, model.frequencia[i], model.meses[x], model.diaSemana[x], @Session["ID"].ToString(), Session["TIPO"].ToString());
                                    }
                                }
                                dataTransf = dataTransf.AddDays(1);

                            }
                            model.horarios[y] = "";
                        }
                        else
                        {
                            model.horarios[y] = "";
                            y = model.horarios.Count;
                        }
                        
                    }
                }
                else 
                {
                    if (model.frequencia[x] == "")
                    {
                        model.frequencia[x] = "diaria";
                    }
                    for (int g = 0; g < model.horarios.Count; g++)
                    {
                        if (model.horarios[g] != "end" && model.horarios[g] != "")
                        {
                            string newFormat = DateTime.ParseExact(model.data[i], "dd/MM/yyyy", CultureInfo.InvariantCulture).ToString("yyyy/MM/dd", CultureInfo.InvariantCulture);
                            dataFormatada = DateTime.Parse(model.data[i] + " " + model.horarios[g].ToString());
                            ModalidadesAulas.NovaModalidade(int.Parse(esporte), int.Parse(Session["ID"].ToString()), dataFormatada, model.frequencia[i].ToString(), int.Parse(model.meses[x].ToString()), model.diaSemana[x].ToString(), @Session["ID"].ToString(), Session["TIPO"].ToString());
                            x++;
                            model.horarios[g] = "";
                        }
                        else if(model.horarios[g] == "end")
                        {
                            model.horarios[g] = "";
                            g = model.horarios.Count;
                        }
                    }
                }
            }
            List<HorariosColaborador> horarios = ModalidadesAulas.ListaHorariosColaborador(Session["ID"].ToString(), @Session["TIPO"].ToString());
            ViewBag.ItemData = horarios.ToList();
            Response.Redirect("~/Home/Modalidades");
        }
        public ActionResult BuscarDiasDisponiveis(String id, String idEsp)
        {
            List<HorariosColaborador> horariosDisp = listagem.Dias(id, idEsp);
            ViewBag.ItemData = horariosDisp.ToList();
            return Json(ViewBag.ItemData, JsonRequestBehavior.AllowGet);
        }
        public ActionResult BuscarHorariosDisponiveis(String dia, int idColab)
        {
            List<HorariosColaborador> horariosDisp = listagem.Horarios(dia, idColab);
            ViewBag.ItemData = horariosDisp.ToList();
            return Json(ViewBag.ItemData, JsonRequestBehavior.AllowGet);
        }
        public ActionResult BuscarDiaSemanaDisponiveis(int id)
        {
            List<RangeHorarios> dias = listagem.diasSemana(id);
            ViewBag.ItemData = dias.ToList();
            return Json(ViewBag.ItemData, JsonRequestBehavior.AllowGet);
        }
        public ActionResult BuscarMesesDisponiveis(String diaSemana)
        {

personal/Views/Servicos/Autorizar.cshtml
@model IList<personal.Models.Colaborador>
@{
    ViewBag.Title = "Autorizar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <link href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link href="~/Content/bootstrap-datepicker.css" rel="stylesheet" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <style type="text/css">
        body {
            color: #404E67;
            background: #F5F7FA;
        }
    </style>
</head>
<body>
    <div class="container col-md-8 col-md-offset-2 " style="margin-top:90px">
        <div class="container">
            <h2>Autorizar</h2>
            <ul class="nav nav-tabs" style="margin-top:7%">
                <li class="active"><a data-toggle="tab" href="#home">Personal Trainer</a></li>
                <li><a data-toggle="tab" onclick="teste()" href="#conc">Novo Esporte</a></li>
            </ul>
            <div class="container" style=" background:#ffffff">
                <div class="tab-content">
                    <div id="home" class="tab-pane fade in active">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">NOME</th>
                                    <th scope="col">N° CREF</th>
                                    <th scope="col">UF CREF</th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>@item.ID_COLABORADOR</td>
                                    <td>@item.NOME<input class="form-control" type="hidden" id="nome" name="nome" value="' + @item.NOME + '"></td>
                                    <td>@item.CREF<input class="form-control" type="hidden" id="cref" name="cref" value="' + @item.CREF + '"></td>
                                    <td>@item.UF_CREF<input class="form-control" type="hidden" id="ufcref" name="ufcref" value="' + @item.UF_CREF + '"></td>
                                    <td>
                                        <button id="btnAv" name="btnAv" class="btn btn-mini" title="Avaliar" style="background: #f9f9f9;padding:0px;margin-left: 12px;" onclick="autoriza(@item.ID_COLABORADOR)">
                                            <i class="fas fa-check"></i>
                                        </button>
                                    </td>
                                    <td>
                                        <button id="btnAv" name="btnAv" class="btn btn-mini" title="Avaliar" style="background: #f9f9f9;padding:0px;margin-left: 12px;" onclick="exclui(@item.ID_COLABORADOR)">
                                            <i class="fas fa-times"></i>
                                        </button>
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                    <div id="conc" class="tab-pane fade"></div>

                    <div class="modal fade" id="ModalAvaliar" name="ModalAvaliar" tabindex="-1" role="dialog" aria-labelledby="ModalAvaliar" aria-hidden="true">
                        <form method="post" action="~/Servicos/NovaModalidade">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="float:right">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        <h5 class="modal-title" id="adicionarHorarios"><b>Avaliar Personal Trainer</b></h5>
                                    </div>
                                    <div class="modal-body">
                                        
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>

            </div>
        </div>
    </div>
    <script type="text/javascript">
        function teste() {
             $.ajax({
                    url: '@Url.Action("AutorizarEsporte", "Servicos")',
                    dataType: 'JSON',
                    data: {},
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        $("#conc").empty();
                        row = "";
                        row +=  '<table class="table table-striped" >' +
                                '<thead>' +
                                '<tr>' +
                                '<th scope="col">ID</th>' +
                                '<th scope="col">ESPORTE</th>' +
                                '</tr>' +
                                '</thead>' +
                                '<tbody>';
                        $.each(data, function (index) {

                                    var esporte = data[index].ID_NOVOESPORTE;
                                    var descricao = data[index].DESCRICAO;

                                    row +=  '<tr>' +
                                            '<td >' + esporte + '<input class="form-control" type="hidden" id="esporte" name="esporte" value="' + esporte + '"> </td>' +
                                            '<td>' + descricao + '<input class="form-control" type="hidden" id="descricao" name="descricao" value="' + descricao + '"> </td>' +
                                            '<td>' +
                                            '<button id="btnAv" name="btnAv" class="btn btn-mini" title="Avaliar" style="background: #f9f9f9;padding:0px;margin-left: 12px;" onclick="carrega()" data-toggle="modal" data-target="#ModalAvaliar">' +
                                            '<i class="fas fa-star"></i>' +
                                            '</button>' +
                                            '</td>' +
                                            '<td>'+
                                            '</td>'+
                                            '</tr>';
                                });
                                row += '</tbody>'+
                                       '</table>';

                           $("#conc").append(row);


                    },
                    error: function () {
                        alert("sem sucesso");
                    }
             });
        }
        function autoriza(id) {
            $.ajax({
                    url: '@Url.Action("salvaAutorizacao", "Servicos")',
                    dataType: 'JSON',
                    data: {idColab: id},
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        location.reload(true);
                    },
                    error: function () {
                    }
             });

        }
        function exclui(id) {
            $.ajax({
                    url: '@Url.Action("bloqueiaAutorizacao", "Servicos")',
                    dataType: 'JSON',
                    data: {idColab: id},
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        location.reload(true);
                    },
                    error: function () {
                    }
             });

        }



    </script>
</body>
</html>

personal/Views/Servicos/MeusServicos.cshtml
@{
    ViewBag.Title = "MeusServicos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="list-group" style="margin-top:100px">
    <a class="list-group-item list-group-item-action flex-column align-items-start active col-md-7 col-md-offset-3 ">

        <div class="d-flex w-100 justify-content-between ">
            <img src="" class="img-rounded float-left" style="width:150px;height:150px" alt="teste">
            <h3 class="mb-1">testeE</h3>
        </div>
        <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
        <small>Donec id elit non mi porta.</small>

        

    </a>

</div>

personal/Views/Servicos/PersonalTrainer.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PersonalTrainer</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>